version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - "5173:5173"
    
    container_name: frontend_container

    networks:
      - mynetwork
    
    volumes:
      - ./frontend:/usr/app
    
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    
    container_name: backend_container

    networks:
      - mynetwork

    volumes:
      - ./backend:/usr/app
    
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_container
    networks:
      - mynetwork
    volumes:
      - mongoData:/data/db

networks:
  mynetwork:

volumes:
  mongoData:
